import type { TemplateDefinition } from "../types";

export const template: TemplateDefinition = {
  id: "vendor_registration",
  version: 2,
  description: "Register a vendor with company contact, services, and payment details.",
  category: "registration",
  categories: ["registration", "event-registration"],
  tags: ["vendors", "events", "procurement"],
  featured: true,
  schema: {
    id: "vendor_registration",
    name: "Vendor Registration",
    elements: [
      {
        id: "vendor_registration_heading",
        name: "Company contact",
        type: "heading",
        label: "Company contact",
        level: 1,
      },
      {
        id: "vendor_registration_intro",
        name: "Company contact intro",
        type: "description",
        label: "Used by event and procurement teams to reach the right person.",
      },
      {
        id: "org_name",
        name: "Organization / business name",
        type: "short_text",
        label: "Organization / business name",
        placeholder: "Prime Mechanical LLC",
        rules: [
          {
            type: "required",
            value: true,
          },
        ],
      },
      {
        id: "contact_name",
        name: "Point of contact",
        type: "short_text",
        label: "Point of contact",
        placeholder: "Jordan Lee",
        rules: [
          {
            type: "required",
            value: true,
          },
        ],
      },
      {
        id: "contact_email",
        name: "Email",
        type: "email",
        label: "Email",
        placeholder: "ops@vendor.com",
        rules: [
          {
            type: "required",
            value: true,
          },
        ],
      },
      {
        id: "phone",
        name: "Phone",
        type: "phone",
        label: "Phone",
        placeholder: "+1 555 123 4567",
      },
      {
        id: "website",
        name: "Company website",
        type: "link",
        label: "Company website",
        placeholder: "https://",
      },
      {
        id: "vendor_registration_page_2",
        name: "Company overview",
        type: "page_break",
        label: "Company overview",
      },
      {
        id: "vendor_registration_heading_2",
        name: "Company overview",
        type: "heading",
        label: "Company overview",
        level: 2,
      },
      {
        id: "vendor_registration_intro_2",
        name: "Company overview intro",
        type: "description",
        label: "Enough context to decide if this vendor belongs on the roster.",
      },
      {
        id: "services",
        name: "Services / goods",
        type: "long_text",
        label: "Services / goods",
        placeholder: "Preventive maintenance, emergency repairs...",
        rules: [
          {
            type: "required",
            value: true,
          },
        ],
      },
      {
        id: "business_type",
        name: "Business type",
        type: "single_select",
        label: "Business type",
        placeholder: "Select a type",
        options: ["Sole proprietor", "LLC", "Corporation", "Partnership", "Nonprofit"],
      },
      {
        id: "service_area",
        name: "Geographic service area",
        type: "short_text",
        label: "Geographic service area",
        placeholder: "Bay Area, national, remote...",
      },
      {
        id: "insurance_status",
        name: "Insurance status",
        type: "single_select",
        label: "Insurance status",
        placeholder: "Select status",
        options: ["Insured", "Not insured", "Pending"],
      },
      {
        id: "license_number",
        name: "License number",
        type: "short_text",
        label: "License number",
        placeholder: "Optional",
      },
      {
        id: "annual_sales",
        name: "Gross annual sales",
        type: "number",
        label: "Gross annual sales",
        placeholder: "250000",
      },
      {
        id: "vendor_registration_page_3",
        name: "Banking and confirmation",
        type: "page_break",
        label: "Banking and confirmation",
      },
      {
        id: "vendor_registration_heading_3",
        name: "Banking and confirmation",
        type: "heading",
        label: "Banking and confirmation",
        level: 2,
      },
      {
        id: "bank_name",
        name: "Bank name",
        type: "short_text",
        label: "Bank name",
        placeholder: "First National",
      },
      {
        id: "beneficiary_name",
        name: "Beneficiary name",
        type: "short_text",
        label: "Beneficiary name",
        placeholder: "Prime Mechanical LLC",
      },
      {
        id: "account_number",
        name: "Account number",
        type: "short_text",
        label: "Account number",
        placeholder: "Last four is enough for now",
      },
      {
        id: "confirmation",
        name: "I confirm this vendor information is accurate",
        type: "single_select",
        label: "I confirm this vendor information is accurate",
        placeholder: "Select to confirm",
        options: ["I confirm"],
        rules: [
          {
            type: "required",
            value: true,
          },
        ],
      },
    ],
    submit: {
      label: "Register vendor",
      size: "full-width",
    },
  },
};
